plugins {
    id 'com.android.application'
}

android {
    namespace 'com.yerel.messenger'
    compileSdk 34

    defaultConfig {
        applicationId 'com.yerel.messenger'
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    signingConfigs {
        release {
            storeFile file('yerel.jks')
            storePassword 'yerel123'
            keyAlias 'yerel'
            keyPassword 'yerel123'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    lint {
        checkReleaseBuilds false
        abortOnError false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
